# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- rakk_accounting_user_property

pool:
  name: Linux-Test-DotNet10

steps:

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls $(build.sourcesDirectory)'
  displayName: List Artifacts
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      sml-cli --version
  displayName: Install SML
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      export ATSCALE_API_TOKEN="5c737097378b4cbe87383b7d45baf4e68096a20f4eb440b898ef3c75704e68f0"
      export ATSCALE_API_URL="https://devatscale.int.saxo/api"
      sml-cli atscale-deploy --catalog-name="balp" --catalog-label="balp"
    workingDirectory: '$(build.sourcesDirectory)'
  displayName: TestDeploy